config/routes.rb
Rails.application.routes.draw do
  resources :coupon_redemptions
  resources :partners
  resources :partners
  resources :offer_saveds
  resources :verification_requests
  resources :verifications
  resources :invitations
  resources :partners
  resources :todos
  resources :releases
  resources :cinemas
  resources :movies
  resources :coupons
  resources :surveys, :attempts
  resources :contests
  resources :valorations
  resources :items
  resources :markets
  resources :offers
  resources :menus
  resources :clientprofiles
  resources :wikis
  resources :panels
  resources :galleries

  resources :profiles do
    resources :reviews, except: [:show, :index]
  end

  resources :posts do
    resources :comments
  end

  resources :events do
    resources :event_comments
  end

  resources :categories

  devise_for :users, controllers: {registrations: "user/registrations",
    omniauth_callbacks: "user/omniauth_callbacks"}

    match 'heart',    to: 'hearts#heart', via: :post
    match 'unheart',  to: 'hearts#unheart', via: :delete
    match 'follow',   to: 'follows#follow', via: :post
    match 'unfollow', to: 'follows#unfollow', via: :delete

    match 'search', to: 'menus#search', via: :get
    match 'tools', to: 'menus#tools', via: :get

    match 'admin_panel', to: 'menus#admin_panel', via: :get
    match 'post_category', to: 'menus#post_category', via: :post
    match 'install', to:'menus#install', via: :get

    match 'redeem', to: 'coupon_redemptions#create',  via: :post
    match 'exchange', to: 'coupon_redemptions#update',  via: :patch

    match 'close_todo', to: 'todos#close', via: :patch
    match 'open_todo', to: 'todos#close', via: :patch

    match 'bienvenido', to: 'menus#user_welcome', via: :get
    match 'myprofile', to: 'menus#myprofile', via: :get

    match 'partners_info', to: 'profiles#info', via: :get

    match 'favorites', to: 'welcome#favorites', via: :get
    match 'terms', to: 'welcome#terms', via: :get
    match 'privacitypolicy', to: 'welcome#privacity', via: :get

    match 'index', to: 'welcome#index', via: :get

    match '/google13e2745398afabff.html',
    :to => proc { |env| [200, {}, ["google-site-verification: /google13e2745398afabff.html"]] }, via: :get

  root 'welcome#index'
end

app/models/verification_request.rb
class VerificationRequest < ApplicationRecord
  belongs_to :user
end

app/controllers/verification_requests_controller.rb
class VerificationRequestsController < ApplicationController
  before_action :set_verification_request, only: [:show, :edit, :update, :destroy]

  # GET /verification_requests
  # GET /verification_requests.json

  # GET /verification_requests/1
  # GET /verification_requests/1.json
  def show
  end

  # GET /verification_requests/new
  def new
    @verification_request = VerificationRequest.new
  end

  # GET /verification_requests/1/edit
  def edit
  end

  # POST /verification_requests
  # POST /verification_requests.json
  def create
    @verification_request = VerificationRequest.new(verification_request_params)

    respond_to do |format|
      if @verification_request.save
        format.html { redirect_to @verification_request, notice: 'Verification request was successfully created.' }
        format.json { render :show, status: :created, location: @verification_request }
      else
        format.html { render :new }
        format.json { render json: @verification_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verification_requests/1
  # PATCH/PUT /verification_requests/1.json
  def update
    respond_to do |format|
      if @verification_request.update(verification_request_params)
        format.html { redirect_to @verification_request, notice: 'Verification request was successfully updated.' }
        format.json { render :show, status: :ok, location: @verification_request }
      else
        format.html { render :edit }
        format.json { render json: @verification_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verification_requests/1
  # DELETE /verification_requests/1.json
  def destroy
    @verification_request.destroy
    respond_to do |format|
      format.html { redirect_to verification_requests_url, notice: 'Verification request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verification_request
      @verification_request = VerificationRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verification_request_params
      params.require(:verification_request).permit(:user_id)
    end
end

app/helpers/verification_requests_helper.rb
module VerificationRequestsHelper
end

app/views/verification_requests/_form.html.erb
<%= simple_form_for(@verification_request) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/verification_requests/edit.html.erb
<h1>Editing Verification Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @verification_request %> |
<%= link_to 'Back', verification_requests_path %>

app/views/verification_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Verification Requests</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @verification_requests.each do |verification_request| %>
      <tr>
        <td><%= verification_request.user %></td>
        <td><%= link_to 'Show', verification_request %></td>
        <td><%= link_to 'Edit', edit_verification_request_path(verification_request) %></td>
        <td><%= link_to 'Destroy', verification_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Verification request', new_verification_request_path %>

app/views/verification_requests/new.html.erb
<h1>New Verification Request</h1>

<%= render 'form' %>

<%= link_to 'Back', verification_requests_path %>

app/views/verification_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @verification_request.user %>
</p>

<%= link_to 'Edit', edit_verification_request_path(@verification_request) %> |
<%= link_to 'Back', verification_requests_path %>