config/routes.rb
Rails.application.routes.draw do
  resources :coupon_redemptions
  resources :partners
  resources :partners
  resources :offer_saveds
  resources :verification_requests
  resources :verifications
  resources :invitations
  resources :partners
  resources :todos
  resources :releases
  resources :cinemas
  resources :movies
  resources :coupons
  resources :surveys, :attempts
  resources :contests
  resources :valorations
  resources :items
  resources :markets
  resources :offers
  resources :menus
  resources :clientprofiles
  resources :wikis
  resources :panels
  resources :galleries

  resources :profiles do
    resources :reviews, except: [:show, :index]
  end

  resources :posts do
    resources :comments
  end

  resources :events do
    resources :event_comments
  end

  resources :categories

  devise_for :users, controllers: {registrations: "user/registrations",
    omniauth_callbacks: "user/omniauth_callbacks"}

    match 'heart',    to: 'hearts#heart', via: :post
    match 'unheart',  to: 'hearts#unheart', via: :delete
    match 'follow',   to: 'follows#follow', via: :post
    match 'unfollow', to: 'follows#unfollow', via: :delete

    match 'search', to: 'menus#search', via: :get
    match 'tools', to: 'menus#tools', via: :get

    match 'admin_panel', to: 'menus#admin_panel', via: :get
    match 'post_category', to: 'menus#post_category', via: :post
    match 'install', to:'menus#install', via: :get

    match 'redeem', to: 'coupon_redemptions#create',  via: :post
    match 'exchange', to: 'coupon_redemptions#update',  via: :patch

    match 'close_todo', to: 'todos#close', via: :patch
    match 'open_todo', to: 'todos#close', via: :patch

    match 'bienvenido', to: 'menus#user_welcome', via: :get
    match 'myprofile', to: 'menus#myprofile', via: :get

    match 'partners_info', to: 'profiles#info', via: :get

    match 'favorites', to: 'welcome#favorites', via: :get
    match 'terms', to: 'welcome#terms', via: :get
    match 'privacitypolicy', to: 'welcome#privacity', via: :get

    match 'index', to: 'welcome#index', via: :get

    match '/google13e2745398afabff.html',
    :to => proc { |env| [200, {}, ["google-site-verification: /google13e2745398afabff.html"]] }, via: :get

  root 'welcome#index'
end

app/models/verification.rb
class Verification < ApplicationRecord
  belongs_to :profile
end

app/controllers/verifications_controller.rb
class VerificationsController < ApplicationController
  before_action :set_verification, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /verifications
  # GET /verifications.json
  def index
    @verifications = Verification.all
  end

  # GET /verifications/1
  # GET /verifications/1.json
  def show
  end

  # GET /verifications/new
  def new
    @verification = Verification.new
  end

  # GET /verifications/1/edit
  def edit
  end

  # POST /verifications
  # POST /verifications.json
  def create
    if current_user.user_lvl >= 3
      @profile = Profile.find(params[:profile_id])
      @verification = Verification.new(profile_id: @profile.id)

      respond_to do |format|
        if @verification.save
          format.html { redirect_to @profile, notice: 'Perfil Verificado' }
          format.json { render :show, status: :created, location: @verification }
        else
          format.html { render :new }
          format.json { render json: @verification.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, notice:'No tienes permiso para esta acción'
    end
  end

  # PATCH/PUT /verifications/1
  # PATCH/PUT /verifications/1.json
  def update
    respond_to do |format|
      if @verification.update(verification_params)
        format.html { redirect_to @verification, notice: 'Verification was successfully updated.' }
        format.json { render :show, status: :ok, location: @verification }
      else
        format.html { render :edit }
        format.json { render json: @verification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verifications/1
  # DELETE /verifications/1.json
  def destroy
    @verification.destroy
    respond_to do |format|
      format.html { redirect_to verifications_url, notice: 'Verification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verification
      @verification = Verification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verification_params
      params.require(:verification).permit(:profile_id)
    end
  end

app/helpers/verifications_helper.rb
module VerificationsHelper
end

app/views/verifications/_form.html.erb
<%= simple_form_for(@verification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :profile %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/verifications/edit.html.erb
<h1>Editing Verification</h1>

<%= render 'form' %>

<%= link_to 'Show', @verification %> |
<%= link_to 'Back', verifications_path %>

app/views/verifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Verifications</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @verifications.each do |verification| %>
      <tr>
        <td><%= verification.profile %></td>
        <td><%= link_to 'Show', verification %></td>
        <td><%= link_to 'Edit', edit_verification_path(verification) %></td>
        <td><%= link_to 'Destroy', verification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Verification', new_verification_path %>

app/views/verifications/new.html.erb
<h1>New Verification</h1>

<%= render 'form' %>

<%= link_to 'Back', verifications_path %>

app/views/verifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @verification.profile %>
</p>

<%= link_to 'Edit', edit_verification_path(@verification) %> |
<%= link_to 'Back', verifications_path %>