config/routes.rb
Rails.application.routes.draw do
  resources :coupon_redemptions
  resources :partners
  resources :partners
  resources :offer_saveds
  resources :verification_requests
  resources :verifications
  resources :invitations
  resources :partners
  resources :todos
  resources :releases
  resources :cinemas
  resources :movies
  resources :coupons
  resources :surveys, :attempts
  resources :contests
  resources :valorations
  resources :items
  resources :markets
  resources :offers
  resources :menus
  resources :clientprofiles
  resources :wikis
  resources :panels
  resources :galleries

  resources :profiles do
    resources :reviews, except: [:show, :index]
  end

  resources :posts do
    resources :comments
  end

  resources :events do
    resources :event_comments
  end

  resources :categories

  devise_for :users, controllers: {registrations: "user/registrations",
    omniauth_callbacks: "user/omniauth_callbacks"}

    match 'heart',    to: 'hearts#heart', via: :post
    match 'unheart',  to: 'hearts#unheart', via: :delete
    match 'follow',   to: 'follows#follow', via: :post
    match 'unfollow', to: 'follows#unfollow', via: :delete

    match 'search', to: 'menus#search', via: :get
    match 'tools', to: 'menus#tools', via: :get

    match 'admin_panel', to: 'menus#admin_panel', via: :get
    match 'post_category', to: 'menus#post_category', via: :post
    match 'install', to:'menus#install', via: :get

    match 'redeem', to: 'coupon_redemptions#create',  via: :post
    match 'exchange', to: 'coupon_redemptions#update',  via: :patch

    match 'close_todo', to: 'todos#close', via: :patch
    match 'open_todo', to: 'todos#close', via: :patch

    match 'bienvenido', to: 'menus#user_welcome', via: :get
    match 'myprofile', to: 'menus#myprofile', via: :get

    match 'partners_info', to: 'profiles#info', via: :get

    match 'favorites', to: 'welcome#favorites', via: :get
    match 'terms', to: 'welcome#terms', via: :get
    match 'privacitypolicy', to: 'welcome#privacity', via: :get

    match 'index', to: 'welcome#index', via: :get

    match '/google13e2745398afabff.html',
    :to => proc { |env| [200, {}, ["google-site-verification: /google13e2745398afabff.html"]] }, via: :get

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:show,:index,:privacity,:terms]
  def index
   @categories = Category.all
   @profiles = Profile.all

    partners = Partner.all
    @promoved_profiles = Profile.where(id: partners.collect(&:profile_id)).all

    @post = Post.new
    @follows = Follow.order(created_at: :desc).all
    @coupons = Coupon.order(created_at: :desc).all


    @comments = Comment.order(created_at: :desc).paginate(page: params[:page], per_page: 10).all


    if user_signed_in?
     @posts = Post.all.paginate(page: params[:page], per_page: 10)
   else
     @posts = Post.order(created_at: :desc).paginate(:page => params[:page], per_page: 10).all
   end

end


def show
  @category = Category.find(params[:id])
end

def favorites
  @posts = Post.where(:profile_id => current_user.follows.collect(&:profile_id) ).order(created_at: :desc).paginate(:page => params[:page], :per_page => 5)
      #this line collect the ids from followed users, then compare with the id of the post's owner and show in to welcome page. (an entire night for make this lol)
      @offers = Offer.where(id: current_user.offer_saveds.collect(&:offer_id) ).order(created_at: :desc).paginate(:page => params[:page], :per_page => 5)
      @offer_saveds = current_user.offer_saveds.all
      @profiles = Profile.where(id: current_user.follows.collect(&:profile_id)).order(created_at: :desc)
    end

    def privacity

    end

    def terms

    end


    private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end

  end

app/helpers/welcome_helper.rb
module WelcomeHelper
	def precio(offer)
		if offer.cordoba == true
			return "#{'C$'}#{offer.precio}"
		else
			return "#{'$'}#{offer.precio}"
		end
	end

	def usr_avatar(user)
		if user.profile.present?
			return user.profile.avatar(:thumb)
		elsif user.clientprofile.present?
			return user.clientprofile.avatar(:thumb)
		else
			return "error"
		end
	end

	def usr_name(user)
		if user.profile.present?
			return user.profile.name
		elsif user.clientprofile.present?
			return "#{user.clientprofile.first_name} #{user.clientprofile.last_name}"
		else
			return "error"
		end
	end

	def welcome_buttons
		if user_signed_in?
			content_tag(:li) do
				link_to('Mis cupones', coupons_path, class:"btn btn-primary")
			end

		else
			content_tag(:li) do
				link_to('Entrar con Facebook', new_user_session_path, class:"btn btn-primary")
			end
		end

	end
end

app/views/welcome/_posts.html.erb
<% if @posts.count < 1%>
  <div class="center">
    <img src="https://cdn3.iconfinder.com/data/icons/map/500/around_me-512.png" alt="" class="responsive-img" />
    <p>
      <b class="grey-text darken-4">Esto está un poco vacío. Toca la brújula y encuenta sitios de tu interés.</b>
    </p>

  </div>
<% else %>
<% @posts.each do |post| %>
  <div class="panel panel-primary">
    <li class="collection-item row">
      <img style="vertical-align: middle; margin-left:2%;height: 40px; width:40px;" src="<%= post.profile.avatar.url(:thumb) %>" alt="" class="circle">
      <b><%= link_to post.profile.name, post.profile %></b>

      <% if user_signed_in? %>
          <% if current_user.id == post.profile.user_id %>
            <%= link_to post, method: :delete, data: { confirm: '¿Borrar tu publicación?' }, class:"right" do%>
              <%= icon('delete', class:"material-icons") %>
            <% end %>

            <%= link_to edit_post_path(post), class:"right" do%>
              <%= icon("pencil-square-o") %>
            <% end %>
          <% end %>
      <% end %>

    </li>

    <li class="collection-item">
      <p class="responsive-text">
        <%= truncate(post.body, length: 140) { link_to "Ver más", post_path(post) } %>
      </p>
      <% if post.pictures.count > 1 %>
        <div class="fotorama" data-nav="thumbs" data-allowfullscreen="true">
            <% post.pictures.each do |pic| %>
              <%= link_to (image_tag(pic.image,lazy: true)) do %>
                <%= image_tag(pic.image(:thumb), lazy: true)%>
              <% end %>
            <% end %>
        </div>
        <% else %>
        <% post.pictures.each do |pic| %>
        <div class="center">
          <%= image_tag(pic.image, class:"responsive-img", lazy: true)%>
        </div>
          <% end %>
      <% end %>
      <% if post.video.present? || post.video =! ""%>
          <% if post.pictures.count < 1 %>
            <%= youtube_video post.video %>
            <% else %>
            Ver video: <a href="<%= post.video%>"><%= post.video %></a>
          <% end %>
      <% end %>

    </li>

      <div class="row" style="margin-bottom:6;">
        <%= div_for(post, class: "col s4 center", style:"max-height: 1px;") do %>
            <%= render partial: "hearts/button", locals: {post: post} %>
          <% end %>
          <div class="col s4 center">
            <%= link_to post do %>
              <%= icon('comments',style:'font-size:2.5rem;') %>
            <% end %>
          </div>
          <div class="col s4 center">
            <%= icon('share-alt',style:'font-size:2.5rem;') %>
          </div>
        </div>
   </div>
   <% end %>
   <% end %>

app/views/welcome/_promo_profiles.html.erb
<div id="owl-promo" class="owl-carousel">
    <% if promoved_profiles.present? %>
    <% promoved_profiles.each do |profile| %>
    <div class="col-xs-12">
        <div class="thumbnail">
            <%= link_to image_tag(profile.avatar(), class:"promo-img responsive-img"), profile %>
            <div class="caption center">
                <b><%= profile.name %> <%= veryfied?(profile) %> </b>
                <br>
                <div class="star-rating star-carousel" data-score=<%= profile.reviews.average(:rating) %>></div>
                <em><%= "#{profile.reviews.length} valoraciones" %></em><br>
                <p>
                    <%= truncate(profile.body ) %><br>
                    <b>Dirección:
                    </b><%= profile.direccion %>
                    <div class="row center">
                        <%= div_for(profile, class:"col-xs-6") do %><%= render partial:'follows/followbtn_small',locals:{profile: profile} %>
                        <% end %>
                        <div class="col-xs-6"><%= link_to 'Ver Más', profile_path(profile), class:"btn btn-primary" %>
                        </div>
                    </div>
                </p>
            </div>
        </div>
    </div>
    <% end %>
    <% else %>
    <div class="alert-alert-warning">No hay contenido para mostrar</div>
    <% end %>
</div>

app/views/welcome/_user_tabs.html.erb
<% if user_signed_in? %>
<div class="sidenav-brand">
	<%= current_user.profile.name %>
</div>

<% else %>
<div class="sidenav-brand row">
	<a href="#" class="link_box"></a>
	<div class="col-xs-4">
		<%= image_tag('icon-user-default.png', class:"img-circle sidenav-img") %>
	</div>
	<div class="col-xs-8">
		<p>
			<b>Invitado</b>
		</p>
	</div>
</div>

<% end %>
<style>
	.link_box{
		width: 100%;
		height: 100%;
	}
</style>

app/views/welcome/favorites.html.erb
<div class="container">
	<div class="page-header"><h3>Favoritos</h3></div>

	<div class="panel panel-default">
		<div class="panel-heading">Ofertas que has guardado</div>
		<div class="panel-body">
			<div id="owl-offers" class="owl-carousel">
				<% if @offers.present? %>
					<% @offers.each do |offer| %>
						<%= render partial:"offers/offer", locals:{offer: offer} %>
					<% end %>
				<% else %>
					<div class="alert alert-warning">No hay contenido para mostrar</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">Tus sitios favoritos</div>
		<div class="panel-body">
			<%= render partial:'welcome/promo_profiles', locals:{promoved_profiles: @profiles} %>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">Publicaciones de Sitios que sigues</div>
		<div class="panel-body">
			<div class="owl-carousel" id="owl-posts">
				<%=if @posts.present? then
					render @posts 
				else
					content_tag(:div, "No hay contenido para mostrar", class:"alert alert-warning")
				end
				%>
			</div>

		</div>
	</div>

</div>

<script>
	$(document).ready(function() {
		$("#owl-posts").owlCarousel();
		$("#owl-offers").owlCarousel();
		$("#owl-promo").owl-carousel();
	});
</script>

app/views/welcome/index.html.erb
<div class="intro-header">
  <div class="intro-message">
    <h2>Nicaragua Live</h2>
    <h3>Encuentra las mejores ofertas en el país</h3>
    <hr class="intro-divider">
    <ul class="list-inline">
    <li><%= link_to 'Ver ofertas', offers_path, class:"btn btn-default" %></li>
    <%= welcome_buttons %>
  </div>
</div>
<div class="container-fluid">
  <!--Tarjetas-->
  <div class="page-header center"><h4><b>Recomendados</b></h4></div>

  <%= render partial:'promo_profiles', locals:{promoved_profiles: @promoved_profiles} %>

</div>

<div class="container-fluid">
<div class="page-header center"><h4><b>Ofertas recientes</b></h4></div>
  <div class="owl-carousel owl-theme">
    <%= render @coupons %>
  </div>
</div>

<div class="container-fluid" >
  <% if user_signed_in? %>
  <div class="page-header center"><h4><b>Publicaciones</b></h4></div>

  <div id="owl-post" class="owl-carousel">
    <%= render @posts %>
  </div>

  <div class="center">
   <ul class="pagination center">
    <div class="apple_pagination">
      <%= will_paginate @posts, container: false %>
    </div>
  </ul>
</div>

<% else %>
<div class="page-header center"><h4><b>Tendencias</b></h4></div>
<div class="center-block">

  <div id="owl-post" class="owl-carousel">
    <%= render @posts.sort_by { |post| post.hearts.count }.reverse %>
  </div>

  <div class="center">
   <ul class="pagination center">
    <div class="apple_pagination">
      <%= will_paginate @posts, container: false %>
    </div>
  </ul>
</div>

</div>
<% end %>
</div>

<div class="container">
<div class="page-header center"><h4><b>Comentarios recientes</b></h4></div>
  <div class="owl-carousel" id="owl-comments">
    <% @comments.each do |comment| %>
    <div class="col-xs-12">
      <%= render partial:"comments/comment_welcome", locals:{comment: comment} %>
    </div>
    <% end %>
  </div>

  <div class="center">
   <ul class="pagination center">
    <div class="apple_pagination">
      <%= will_paginate @comments, container: false %>
    </div>
  </ul>
</div>
</div>

<script>
  $("img.lazy").lazyload({
    threshold : 200
  });

$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:3
        }
    }
})

</script>

app/views/welcome/terms.html.erb
<div class="container">
	<%= render 'welcome/terms' %>
</div>