config/routes.rb
Rails.application.routes.draw do
  resources :coupon_redemptions
  resources :partners
  resources :partners
  resources :offer_saveds
  resources :verification_requests
  resources :verifications
  resources :invitations
  resources :partners
  resources :todos
  resources :releases
  resources :cinemas
  resources :movies
  resources :coupons
  resources :surveys, :attempts
  resources :contests
  resources :valorations
  resources :items
  resources :markets
  resources :offers
  resources :menus
  resources :clientprofiles
  resources :wikis
  resources :panels
  resources :galleries

  resources :profiles do
    resources :reviews, except: [:show, :index]
  end

  resources :posts do
    resources :comments
  end

  resources :events do
    resources :event_comments
  end

  resources :categories

  devise_for :users, controllers: {registrations: "user/registrations",
    omniauth_callbacks: "user/omniauth_callbacks"}

    match 'heart',    to: 'hearts#heart', via: :post
    match 'unheart',  to: 'hearts#unheart', via: :delete
    match 'follow',   to: 'follows#follow', via: :post
    match 'unfollow', to: 'follows#unfollow', via: :delete

    match 'search', to: 'menus#search', via: :get
    match 'tools', to: 'menus#tools', via: :get

    match 'admin_panel', to: 'menus#admin_panel', via: :get
    match 'post_category', to: 'menus#post_category', via: :post
    match 'install', to:'menus#install', via: :get

    match 'redeem', to: 'coupon_redemptions#create',  via: :post
    match 'exchange', to: 'coupon_redemptions#update',  via: :patch

    match 'close_todo', to: 'todos#close', via: :patch
    match 'open_todo', to: 'todos#close', via: :patch

    match 'bienvenido', to: 'menus#user_welcome', via: :get
    match 'myprofile', to: 'menus#myprofile', via: :get

    match 'partners_info', to: 'profiles#info', via: :get

    match 'favorites', to: 'welcome#favorites', via: :get
    match 'terms', to: 'welcome#terms', via: :get
    match 'privacitypolicy', to: 'welcome#privacity', via: :get

    match 'index', to: 'welcome#index', via: :get

    match '/google13e2745398afabff.html',
    :to => proc { |env| [200, {}, ["google-site-verification: /google13e2745398afabff.html"]] }, via: :get

  root 'welcome#index'
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :profiles
	has_many :users
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:show,:index]
  #before_action :authenticate_master_admin!, except: [:show,:index]
  # GET /categories
  # GET /categories.json
  respond_to
  def index
    @categories = Category.all
    @promoved_profiles = Profile.where.not(aasm_campaign: 'noone')
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    if current_user.user_lvl >= 3
      @category = Category.new
    else
      redirect_to root_path, notice:"No tienes permisos para esta accion"
    end
  end

  # GET /categories/1/edit
  def edit
    unless current_user.user_lvl >= 3
      redirect_to root_path, notice:"No tienes permisos para esta accion"
    end
  end

  # POST /categories
  # POST /categories.json
  def create
    @categories = Category.order(created_at: :asc).all
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_panel_path, notice: 'La categoria se creó correctamente' }
        format.json { render :show, status: :created, location: admin_panel_path }
        format.js
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_panel_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @categories = Category.all
    @category.destroy
      respond_to do |format|
        format.html { redirect_to admin_panel_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :cover, :icon)
    end

    def check_admin
      if client_signed_in?
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nombre" %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label "Icono"%><br>
    <%= f.text_field :icon %>
  </div>

  <div class="actions">
    <%= f.submit "Guardar", class:"btn-large green" %>
    <%= link_to "Volver", panels_path, class:"btn-large red" %>
  </div>
<% end %>

app/views/categories/_profiles.html.erb
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <%= link_to image_tag(profile.avatar(), class:"promo-img responsive-img"), profile %>
        <div class="caption center">
            <b><%= profile.name %><%= veryfied?(profile) %></b>
            <br>
            <div class="star-rating" data-score=<%= profile.reviews.average(:rating) %>></div>
            <em><%= "#{profile.reviews.length} valoraciones" %></em><br>
            <p>
                <%= truncate(profile.body ) %><br>
                <b>Dirección:
                </b><%= profile.direccion %>
                <div class="center"><%= link_to 'Ver Más', profile_path(profile), class:"btn btn-primary" %></div>
            </p>
        </div>
    </div>
</div>

app/views/categories/create.js.erb
$("#categories_table").html("<%= escape_javascript(render partial:'menus/admin_panel/categories', locals:{categories: @categories} ) %>");

var $toastContent = $('<span>La categoría se creó.</span>');
Materialize.toast($toastContent, 5000);

app/views/categories/destroy.js.erb
$("#categories_table").html("<%= escape_javascript(render partial:'menus/admin_panel/categories', locals:{categories: @categories} ) %>");

var $toastContent = $('<span>La categoría se eliminó.</span>');
Materialize.toast($toastContent, 5000);

app/views/categories/edit.html.erb
<div class="container">

<h5>Editando Categoría</h5>

<%= render 'form' %>

</div>

app/views/categories/index.html.erb
<div class="container">
<div class="page-header"><h4>Descubrir</h4></div>

    <%= form_tag(profiles_path, method: "get", id: "search-form") do %>
    <h5 class="grey-text darken-4">Buscar</h5>
    <%= text_field_tag :query, params[:query], placeholder: "Buscar...",class:"grey-text darken-4", style:"max-width: 50%;" %>
    <%= submit_tag "Buscar", class:"btn red" %>
    <% end %>
    <p id="notice"><%= notice %></p>

    <h5>Categorías</h5>

    <div class="list-group">
        <% @categories.each do |category| %>
        <a href="<%= category_path(category) %>" class="list-group-item">
            <%= icon(category.icon,style:'font-size:2rem;') %>
            <%= category.name %>
        </a>
        <% end %>
    </div>
    <div>
        <%= render partial:'/welcome/promo_profiles', locals:{promoved_profiles: @promoved_profiles} %>
    </div>
</div>
<script>
    $('.star-rating').raty({

        readOnly: true,
        score: function () {
            return $(this).attr('data-score');
        }
    });
</script>

app/views/categories/new.html.erb
<div class="container">
<h5>Añadir Nueva Categoria</h5>

<%= render 'form' %>

</div>

app/views/categories/show.html.erb
<div class="container">
	<h5 class="grey-text darken-4"><%= @category.name %></h5>

	<% unless @category.profiles.any? %>
	<div class="center">
		<h4>¡Enhorabuena!</h4>
		<em>Aún no hay ningun negocio en esta categoría. Es tu oportunidad para ser el primero.</em><br>
		<%= image_tag('business.gif', class:"responsive-img") %><br>
		<div style="margin-top:5%">
			<% unless user_signed_in? %>
				<%= link_to "Ser el primero", new_user_registration_path, class:"btn green" %>
				<% else %>
				<%= link_to "Ser el primero", edit_user_registration_path, class:"btn green" %>
			<% end %>
		</div>
	</div>
	<% end %>
  
  <div class="center">
    <% @category.profiles.each do |profile| %>
      <%= render partial:'profiles', locals:{profile: profile} %>
    <% end %>
  </div>

</div>
</div>
<script>
  $('.star-rating').raty({

   readOnly: true,
   score: function() {
    return $(this).attr('data-score');
  }
});
</script>